# 1. Import and Install Dependencies

In [ ]:
%pip install tensorflow opencv-python mediapipe sklearn 

In [1]:
import cv2
import numpy as np
import os
import mediapipe as mp

# 2. Keypoints using MediaPipe Holistic Holistic

In [4]:
# Build Keypoints using MP Holistic
mp_holistic = mp.solutions.holistic  # Holistic model
mp_drawing = mp.solutions.drawing_utils  # Drawing utilities

In [5]:
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # COLOR CONVERSION BGR 2 RGB
    image.flags.writeable = False                   # Image is no longer writable
    results = model.process(image)                  # Make prediction
    image.flags.writeable = True                    # Image is now writable
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)  # COLOR CONVERSION RGB 2 BGR
    return image, results

In [18]:
mp_drawing.draw_landmarks??

Signature:
mp_drawing.draw_landmarks(
    image: numpy.ndarray,
    landmark_list: mediapipe.framework.formats.landmark_pb2.NormalizedLandmarkList,
    connections: Union[List[Tuple[int, int]], NoneType] = None,
    landmark_drawing_spec: Union[mediapipe.python.solutions.drawing_utils.DrawingSpec, Mapping[int, mediapipe.python.solutions.drawing_utils.DrawingSpec]] = DrawingSpec(color=(0, 0, 255), thickness=2, circle_radius=2),
    connection_drawing_spec: Union[mediapipe.python.solutions.drawing_utils.DrawingSpec, Mapping[Tuple[int, int], mediapipe.python.solutions.drawing_utils.DrawingSpec]] = DrawingSpec(color=(224, 224, 224), thickness=2, circle_radius=2),
)
Source:   
def draw_landmarks(
    image: np.ndarray,
    landmark_list: landmark_pb2.NormalizedLandmarkList,
    connections: Optional[List[Tuple[int, int]]] = None,
    landmark_drawing_spec: Union[DrawingSpec,
                                 Mapping[int, DrawingSpec]] = DrawingSpec(
                                     color

In [3]:
def draw_styled_landmarks(image, results):
    # Draw face connections
    mp_drawing.draw_landmarks(
        image, results.face_landmarks, 
        mp_holistic.FACEMESH_CONTOURS, # draw connection
        mp_drawing.DrawingSpec(color=(13, 126, 251), thickness=1, circle_radius=3), # color of landmark
        mp_drawing.DrawingSpec(color=(21, 164, 243), thickness=1, circle_radius=3) # color of connection
        )
    # Draw pose connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                              mp_drawing.DrawingSpec(color=(233, 171, 69), thickness=2, circle_radius=4),
                              mp_drawing.DrawingSpec(color=(243, 71, 53), thickness=2, circle_radius=2) 
                              )
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS,
                              mp_drawing.DrawingSpec(color=(245, 51, 143), thickness=2, circle_radius=4),
                              mp_drawing.DrawingSpec(color=(156, 8, 78), thickness=2, circle_radius=2)
                              )
    # Draw right hand connections
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS,
                              mp_drawing.DrawingSpec(color=(65, 12, 152), thickness=2, circle_radius=4),
                              mp_drawing.DrawingSpec(color=(169, 123, 245), thickness=2, circle_radius=2)
                              )

In [5]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)

        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

In [9]:
len(results.pose_landmarks.landmark)

33

In [10]:
results.pose_landmarks

landmark {
  x: 0.5327727794647217
  y: 0.593017578125
  z: -0.9977322816848755
  visibility: 0.9998844265937805
}
landmark {
  x: 0.5539776086807251
  y: 0.5203202366828918
  z: -0.9214475750923157
  visibility: 0.999851405620575
}
landmark {
  x: 0.5705116391181946
  y: 0.5207399129867554
  z: -0.9214445352554321
  visibility: 0.9998733401298523
}
landmark {
  x: 0.5868312120437622
  y: 0.5214189887046814
  z: -0.9211267232894897
  visibility: 0.9998610019683838
}
landmark {
  x: 0.4983668923377991
  y: 0.522924542427063
  z: -0.9373672604560852
  visibility: 0.9998049139976501
}
landmark {
  x: 0.4777977466583252
  y: 0.5245007872581482
  z: -0.9366471171379089
  visibility: 0.9997720122337341
}
landmark {
  x: 0.4586264193058014
  y: 0.5265353322029114
  z: -0.9370376467704773
  visibility: 0.9997212290763855
}
landmark {
  x: 0.6070511937141418
  y: 0.5508447289466858
  z: -0.46343594789505005
  visibility: 0.999880313873291
}
landmark {
  x: 0.428702175617218
  y: 0.5603517293930

In [11]:
len(results.face_landmarks.landmark)

468

In [12]:
results.face_landmarks

landmark {
  x: 0.5420975089073181
  y: 0.6517890095710754
  z: -0.0291049275547266
}
landmark {
  x: 0.5440817475318909
  y: 0.6015976071357727
  z: -0.05067422613501549
}
landmark {
  x: 0.5412169694900513
  y: 0.6168423891067505
  z: -0.027173683047294617
}
landmark {
  x: 0.5326067209243774
  y: 0.5545877814292908
  z: -0.03863728418946266
}
landmark {
  x: 0.5442484617233276
  y: 0.5867592692375183
  z: -0.05379938334226608
}
landmark {
  x: 0.5430708527565002
  y: 0.5676182508468628
  z: -0.04981427267193794
}
landmark {
  x: 0.5388708114624023
  y: 0.5215307474136353
  z: -0.02296721749007702
}
landmark {
  x: 0.4615878760814667
  y: 0.5195943117141724
  z: 0.00459650531411171
}
landmark {
  x: 0.5374985337257385
  y: 0.48329541087150574
  z: -0.015603138133883476
}
landmark {
  x: 0.5375872254371643
  y: 0.46315160393714905
  z: -0.016871899366378784
}
landmark {
  x: 0.5359849333763123
  y: 0.39514029026031494
  z: -0.004995225928723812
}
landmark {
  x: 0.5420064926147461
  y

In [13]:
len(results.left_hand_landmarks.landmark)

21

In [14]:
results.left_hand_landmarks

landmark {
  x: 0.8041965365409851
  y: 0.6758117079734802
  z: 3.0142993523440964e-07
}
landmark {
  x: 0.731116533279419
  y: 0.6317991018295288
  z: -0.015956426039338112
}
landmark {
  x: 0.6803468465805054
  y: 0.5401105880737305
  z: -0.017098156735301018
}
landmark {
  x: 0.6556889414787292
  y: 0.4617180824279785
  z: -0.01788165792822838
}
landmark {
  x: 0.6243334412574768
  y: 0.4157320261001587
  z: -0.01788785122334957
}
landmark {
  x: 0.7254391312599182
  y: 0.4279519319534302
  z: 0.0019368721405044198
}
landmark {
  x: 0.704042375087738
  y: 0.3343159556388855
  z: -0.008079254068434238
}
landmark {
  x: 0.6950739026069641
  y: 0.2775532603263855
  z: -0.019337309524416924
}
landmark {
  x: 0.6908588409423828
  y: 0.22827386856079102
  z: -0.028283871710300446
}
landmark {
  x: 0.7717407941818237
  y: 0.4150421619415283
  z: -0.0014333523577079177
}
landmark {
  x: 0.7568906545639038
  y: 0.31036680936813354
  z: -0.005469678435474634
}
landmark {
  x: 0.74915730953216

In [20]:
pose=[]
for res in results.pose_landmarks.landmark:
    test = np.array([res.x, res.y, res.z, res.visibility])
    pose.append(test)

In [21]:
pose

[array([ 0.53277278,  0.59301758, -0.99773228,  0.99988443]),
 array([ 0.55397761,  0.52032024, -0.92144758,  0.99985141]),
 array([ 0.57051164,  0.52073991, -0.92144454,  0.99987334]),
 array([ 0.58683121,  0.52141899, -0.92112672,  0.999861  ]),
 array([ 0.49836689,  0.52292454, -0.93736726,  0.99980491]),
 array([ 0.47779775,  0.52450079, -0.93664712,  0.99977201]),
 array([ 0.45862642,  0.52653533, -0.93703765,  0.99972123]),
 array([ 0.60705119,  0.55084473, -0.46343595,  0.99988031]),
 array([ 0.42870218,  0.56035173, -0.52494431,  0.99984819]),
 array([ 0.56509244,  0.66328436, -0.8252058 ,  0.99985027]),
 array([ 0.49417752,  0.66007799, -0.84456557,  0.9998464 ]),
 array([ 0.73574281,  0.89329821, -0.19237098,  0.99899298]),
 array([ 0.2824266 ,  0.89611262, -0.23681793,  0.9860754 ]),
 array([ 0.96239054,  1.1089685 , -0.64254135,  0.95112419]),
 array([ 0.18617654,  1.39276266, -0.12452877,  0.20089677]),
 array([ 0.83022821,  0.68897283, -1.17648244,  0.99310488]),
 array([

In [23]:
pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark])
pose

array([[ 5.32772779e-01,  5.93017578e-01, -9.97732282e-01,
         9.99884427e-01],
       [ 5.53977609e-01,  5.20320237e-01, -9.21447575e-01,
         9.99851406e-01],
       [ 5.70511639e-01,  5.20739913e-01, -9.21444535e-01,
         9.99873340e-01],
       [ 5.86831212e-01,  5.21418989e-01, -9.21126723e-01,
         9.99861002e-01],
       [ 4.98366892e-01,  5.22924542e-01, -9.37367260e-01,
         9.99804914e-01],
       [ 4.77797747e-01,  5.24500787e-01, -9.36647117e-01,
         9.99772012e-01],
       [ 4.58626419e-01,  5.26535332e-01, -9.37037647e-01,
         9.99721229e-01],
       [ 6.07051194e-01,  5.50844729e-01, -4.63435948e-01,
         9.99880314e-01],
       [ 4.28702176e-01,  5.60351729e-01, -5.24944305e-01,
         9.99848187e-01],
       [ 5.65092444e-01,  6.63284361e-01, -8.25205803e-01,
         9.99850273e-01],
       [ 4.94177520e-01,  6.60077989e-01, -8.44565570e-01,
         9.99846399e-01],
       [ 7.35742807e-01,  8.93298209e-01, -1.92370981e-01,
      

In [25]:
pose.shape

(33, 4)

In [27]:
pose = np.array([[res.x, res.y, res.z, res.visibility] 
    for res in results.pose_landmarks.landmark]).flatten()
pose.shape

(132,)

# 3. Extract Keypoint Values

In [2]:
def extract_keypoints(results):
    pose = np.array([[res.x, res.y, res.z, res.visibility] 
        for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)

    face = np.array([[res.x, res.y, res.z] 
        for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)

    lh = np.array([[res.x, res.y, res.z] 
        for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)

    rh = np.array([[res.x, res.y, res.z] 
        for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
        
    return np.concatenate([pose, face, lh, rh])

In [29]:
result_test = extract_keypoints(results)

In [30]:
result_test.shape

(1662,)

In [31]:
result_test

array([ 0.53277278,  0.59301758, -0.99773228, ...,  0.        ,
        0.        ,  0.        ])

# 4. Setup Folders for Collection

In [46]:
# Path for exported data, numpy arrays
DATA_PATH = os.path.join('Data') 

# Actions that we try to detect
actions = np.array(['Not Detected','Good Luck','Sick','Thank You','Sorry','Sad'])

# number of video
no_sequences = 50

# Videos are going to be 30 frames in length
sequence_length = 30

In [47]:
for action in actions: 
    for sequence in range(no_sequences):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

# 5. Collect Keypoint Values for Training and Testing

In [ ]:
cap = cv2.VideoCapture(0)

# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:

    # Loop through actions
    for action in actions:
        # Loop through number of video 
        for sequence in range(no_sequences):
            # Loop through sequence length
            for frame_num in range(sequence_length):

                # Read feed
                ret, frame = cap.read()

                # Make detections
                image, results = mediapipe_detection(frame, holistic)

                # Draw landmarks
                draw_styled_landmarks(image, results)
                
                # Apply wait logic
                if frame_num == 0: 
                    cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                    cv2.waitKey(2000)
                else: 
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                
                # Export keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)

                # Break
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
                    
    cap.release()
    cv2.destroyAllWindows()

In [ ]:
cap.release()
cv2.destroyAllWindows()

# 6. Preprocess Data and Create Labels and Features

In [9]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [48]:
label_map = {label:num for num, label in enumerate(actions)}

In [49]:
label_map

{'Not Detected': 0,
 'Good Luck': 1,
 'Sick': 2,
 'Thank You': 3,
 'Sorry': 4,
 'Sad': 5}

In [50]:
sequences, labels = [], []
for action in actions:
    for sequence in range(no_sequences):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [57]:
np.array(sequences).shape

(300, 30, 1662)

In [58]:
np.array(labels).shape

(300,)

In [59]:
X = np.array(sequences)

In [60]:
X.shape

(300, 30, 1662)

In [61]:
y = to_categorical(labels).astype(int)

In [62]:
y

array([[1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1]])

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [64]:
y_test.shape

(60, 6)

# 7. Build and Train LSTM Neural Network

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard

In [65]:
log = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log)

In [66]:
model = Sequential()
model.add(LSTM(32, return_sequences=True, activation='sigmoid', input_shape=(30,1662)))
model.add(LSTM(64, return_sequences=True, activation='sigmoid'))
model.add(LSTM(128, return_sequences=False, activation='sigmoid'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))

In [67]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [68]:
model.fit(X_train, y_train, epochs=500, callbacks=[tb_callback])

Epoch 1/500
8/8 [==============================] - 3s 43ms/step - loss: 1.8008 - categorical_accuracy: 0.1708
Epoch 2/500
8/8 [==============================] - 0s 41ms/step - loss: 1.7982 - categorical_accuracy: 0.1750
Epoch 3/500
8/8 [==============================] - 0s 41ms/step - loss: 1.7977 - categorical_accuracy: 0.1500
Epoch 4/500
8/8 [==============================] - 0s 42ms/step - loss: 1.7959 - categorical_accuracy: 0.1792
Epoch 5/500
8/8 [==============================] - 0s 39ms/step - loss: 1.7926 - categorical_accuracy: 0.1792
Epoch 6/500
8/8 [==============================] - 0s 38ms/step - loss: 1.7906 - categorical_accuracy: 0.1792
Epoch 7/500
8/8 [==============================] - 0s 40ms/step - loss: 1.7880 - categorical_accuracy: 0.1792
Epoch 8/500
8/8 [==============================] - 0s 44ms/step - loss: 1.7852 - categorical_accuracy: 0.2542
Epoch 9/500
8/8 [==============================] - 0s 39ms/step - loss: 1.7768 - categorical_accuracy: 0.2875
Epoch 10/5

In [69]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 30, 32)            216960    
                                                                 
 lstm_4 (LSTM)               (None, 30, 64)            24832     
                                                                 
 lstm_5 (LSTM)               (None, 128)               98816     
                                                                 
 dense_4 (Dense)             (None, 128)               16512     
                                                                 
 dense_5 (Dense)             (None, 64)                8256      
                                                                 
 dense_6 (Dense)             (None, 32)                2080      
                                                                 
 dense_7 (Dense)             (None, 6)                

# 8. Make Predictions

In [70]:
res = model.predict(X_test)

In [73]:
actions[np.argmax(res[40])]

'Good Luck'

In [74]:
actions[np.argmax(y_test[40])]

'Good Luck'

# 9. Save Weights

In [75]:
model.save('6_gestures.h5')

In [82]:
del model

Load Model

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [7]:
model = Sequential()
model.add(LSTM(32, return_sequences=True, activation='sigmoid', input_shape=(30,1662)))
model.add(LSTM(64, return_sequences=True, activation='sigmoid'))
model.add(LSTM(128, return_sequences=False, activation='sigmoid'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(6, activation='softmax'))

In [8]:
model.load_weights('6_gestures.h5')

In [9]:
actions = np.array(['No Detected','Good Luck','Sick','Thank You','Sorry','Sad'])

# 10. Evaluation using Confusion Matrix and Accuracy

In [33]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [76]:
y_predict = model.predict(X_test)

In [77]:
y_true = np.argmax(y_test, axis=1).tolist()
y_predict = np.argmax(y_predict, axis=1).tolist()

In [78]:
multilabel_confusion_matrix(y_true, y_predict)

array([[[50,  0],
        [ 0, 10]],

       [[48,  0],
        [ 0, 12]],

       [[53,  0],
        [ 0,  7]],

       [[51,  0],
        [ 0,  9]],

       [[46,  0],
        [ 0, 14]],

       [[52,  0],
        [ 0,  8]]], dtype=int64)

In [79]:
accuracy_score(y_true, y_predict)

1.0

# 11. Test in Real Time

In [10]:
colors = [(90, 90, 244),(113,126,247), (119,241,197), (241,219,147), (247, 175, 223),(171,171,251)]
def prob_viz(res, actions, input_frame, colors):
    output_frame = input_frame.copy()
    for num, prob in enumerate(res):
        cv2.rectangle(output_frame, (0,60+num*40), ((int(prob*100)), 90+num*40), colors[num], -1)
        cv2.putText(output_frame, actions[num], (0, 85+num*40), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,0), 1, cv2.LINE_AA)
        
    return output_frame

In [11]:
# 1. New detection variables
sequence = []
sentence = []
threshold = 0.9

cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)
        
        # 2. Prediction logic
        keypoints = extract_keypoints(results)
        sequence.append(keypoints)
        sequence = sequence[-30:]
        
        if len(sequence) == 30:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]            
            
        #3. Viz logic
            if res[np.argmax(res)] > threshold:
                 sentence.append(actions[np.argmax(res)])
                
            if len(sentence) > 1: 
                sentence = sentence[-1:]

            # Viz probabilities
            image = prob_viz(res, actions, image, colors)
            
        cv2.rectangle(image, (0,0), (640, 40), (125, 125, 125), -1)
        cv2.putText(image, ''.join(sentence), (250,30), 
                       cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 2, cv2.LINE_AA)
        
        
        # Show to screen
        cv2.imshow('Test in Real Time', image)

        # Break
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

In [18]:
cap.release()
cv2.destroyAllWindows()

In [86]:
model.predict(np.expand_dims(X_test[0], axis=0))

array([[1.1493639e-33, 1.5936225e-11, 8.4717498e-25, 3.2219325e-06,
        9.9998522e-01, 1.1565317e-05]], dtype=float32)